- type: entity
  id: CrateServiceCleanades
  parent: CratePlastic
  name: janitorial cleanades crate
  description: And Nanotrasen(tm) said, let there be soap. And there was soap.
  components:
  - type: StorageFill
    contents:
      - id: BoxCleanerGrenades
        amount: 2

- type: entity
  id: CrateServiceJanitorialHardsuit
  parent: CrateTrashCartJani
  name: janitorial hardsuit crate
  description: A necessity for any janitor trying to keep the outside of the station as spotless as the inside.
  components:
  - type: StorageFill
    contents:
      - id: ClothingOuterHardsuitJanitor
        amount: 1

- type: entity
  id: CrateServiceMaintBarKit
  parent: CratePlastic
  name: maintenance bar kit
  description: A crate to carry on the tradition of bar engineering. Drinks not included.
  components:
    - type: StorageFill
      contents:
        - id: BoozeDispenserMachineCircuitboard
        - id: SodaDispenserMachineCircuitboard
        - id: MaterialWoodPlank
        - id: MaterialCloth10
        - id: DrinkGlass
          amount: 5
        - id: Spoon
        - id: DrinkShaker
        - id: CustomDrinkJug
          amount: 2
