- type: antag
  id: SubvertedSilicon
  name: roles-antag-subverted-silicon-name
  antagonist: true
  playTimeTracker: AntagSubvertedSilicon # imp
  setPreference: false
  objective: roles-antag-subverted-silicon-objective
